"""mapa del campus: campus_locations y coordenadas de edificios

Revision ID: 3cae46324d1a
Revises: ac782006631c
Create Date: 2026-09-07 18:40:58.638329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cae46324d1a'
down_revision = 'ac782006631c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('BIBLIOTECA', 'COMEDOR', 'SALA_ESTUDIO', 'OFICINA', 'BANO', 'LABORATORIO', 'OTRO', name='locationtype'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('buildings', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('buildings', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'longitude')
    op.drop_column('buildings', 'latitude')
    op.drop_table('campus_locations')
    # ### end Alembic commands ###
