"""modelo academico completo

Revision ID: 544f5e784908
Revises: 
Create Date: 2026-08-14 18:17:03.570259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544f5e784908'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ubicacion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('careers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('classrooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('building_id', sa.UUID(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'codigo', name='uq_classroom_building_codigo')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('legajo', sa.String(), nullable=False),
    sa.Column('dni', sa.String(), nullable=True),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('anio_ingreso', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('legajo'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('teacher_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('legajo_docente', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legajo_docente'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('commissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('teacher_profile_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVA', 'FINALIZADA', 'CANCELADA', name='commissionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_profile_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_profile_id', sa.UUID(), nullable=False),
    sa.Column('commission_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('estado', sa.Enum('PRESENTE', 'TARDE', 'AUSENTE', name='attendancestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_profile_id', sa.UUID(), nullable=False),
    sa.Column('commission_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('CURSANDO', 'APROBADA', 'DESAPROBADA', 'LIBRE', name='enrollmentstatus'), nullable=False),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_profile_id', 'commission_id', name='uq_enrollment_student_commission')
    )
    op.create_table('schedule_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commission_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('dia', sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', name='dayofweek'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_slots')
    op.drop_table('enrollments')
    op.drop_table('attendances')
    op.drop_table('commissions')
    op.drop_table('teacher_profiles')
    op.drop_table('subjects')
    op.drop_table('student_profiles')
    op.drop_table('classrooms')
    op.drop_table('careers')
    op.drop_table('buildings')
    # ### end Alembic commands ###
