"""attendance: restriccion anti-duplicados

Revision ID: ac782006631c
Revises: d42a2e88c870
Create Date: 2026-09-04 20:54:37.009394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac782006631c'
down_revision = 'd42a2e88c870'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_attendance_student_commission_fecha', 'attendances', ['student_profile_id', 'commission_id', 'fecha'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_attendance_student_commission_fecha', 'attendances', type_='unique')
    # ### end Alembic commands ###
